### ISSUE TITLE
SendTimestamps : crash after reopening the window

### ISSUE THREAD

**Issue by Wiltoga** [Taimoor-Tariq/BetterDiscordStuff#1]
Discord crashes when reopening the timestamp selection window under certain circumstances :
* First open the window, set an hour (`4`for example) then the minutes (`16`for example)
![image](https://user-images.githubusercontent.com/30344403/147555824-bf03c3eb-b59c-4261-9a2d-16f61e85a0bf.png)
* remove the minutes (with backspace)
![image](https://user-images.githubusercontent.com/30344403/147555870-db63cf9e-6426-4f17-8458-860a85bcfbc2.png)
* close the window (`Escape`, Cancel, Enter, ...)
* reopen the window → crash

Tested with no other active plugin.

**Comment by Taimoor-Tariq** [comment]
Fixed!
