### ISSUE TITLE
[Enhancement] SendTimestamps: Add formatting option and preview

### ISSUE THREAD

**Issue by l0c4lh057** [Taimoor-Tariq/BetterDiscordStuff#1]
The plugin only uses the default formatting, but discord supports [more than just that](https://discord.com/developers/docs/reference#message-formatting-timestamp-styles). An option to choose which one you want would be nice to have.

![grafik](https://user-images.githubusercontent.com/42084688/127888097-5bab0255-d7e9-4af4-9ccc-f3fbe5003355.png)
![grafik](https://user-images.githubusercontent.com/42084688/127888124-9e66f915-5197-436e-987e-a3fd6b19ac7c.png)

Just adding a dropdown with the options discord provides and then adding the selected option would be enough. However it would also be nice if the user would see how it will look then, which could be done by just adding a preview to the menu.

**Comment by Taimoor-Tariq** [comment]
Thanks for letting me know.
I will look into it and add it soon.

**Comment by Taimoor-Tariq** [comment]
I just found out about that yesterday.
I added it to the plugin from your fork.
