### ISSUE TITLE
[Send Timestamps] - Cannot open setting error

### ISSUE THREAD

**Issue by BigFlubba** [Taimoor-Tariq/BetterDiscordStuff#12]
After trial and error, I cannot open the settings for this plugin and I believe that this was caused by the latest discord update but I am not sure.

**Comment by Taimoor-Tariq** [comment]
This is a known bug and I'm trying to fix it.
The settings is fully functional, its just that sometimes it does not wanna open the first time you click it but opens the next time you do.
Im trying to figure out why so please be patient and thank you for using my plugin.
