### ISSUE TITLE
Should be fixed in the latest update. 🙂

### ISSUE THREAD

**Issue by nosut** [Taimoor-Tariq/BetterDiscordStuff#13]
Should be fixed in the latest update. 🙂

_Originally posted by @Taimoor-Tariq in https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/8#issuecomment-1012960299_

Still having this(message box formatting) issue today in at least 1 server.
https://i.imgur.com/qR2G9Tr.png

**Comment by Taimoor-Tariq** [comment]
It is likely caused due to you not having the **attach button**, May I ask you how you got rid of it?

**Comment by nosut** [comment]
I didn't. In other servers both buttons are still there. I think this channel doesn't allow any type of attachments. Could that remove the button?

**Comment by Taimoor-Tariq** [comment]
I fixed it in the latest update

Let me know if there is anything else I can help you with
