### ISSUE TITLE
Make the time setting look more like a clock

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#13]
Make the field look like <hh> : <mm>.

- As it is now, if minutes are < 10, it just uses one digit.
- Add a ":" between the fields.
- Personally, I don't see using the + / - buttons.  I'd rather type the time in.

I really like the interface to "HammerTime", but having your plugin integrated into Discord is much cooler.
If you need a link, here's one to HammerTime: https://hammertime.djdavid98.art/

I'll echo the other user's open issue about having it be 12 hour mode.  That's what I'm used to and I often make mistakes when I'm talking about times > 1200.

Thanks for an awesome plugin!

**Comment by Taimoor-Tariq** [comment]
Hey,

Thanks for the suggestions, I will work on them in the next few weeks.
