### ISSUE TITLE
Could not open settings, Use button also not showing

### ISSUE THREAD

**Issue by nosut** [Taimoor-Tariq/BetterDiscordStuff#14]
I noticed that the button was no longer showing today. I tried to open the settings and that would not work as well.
I fully uninstalled and reinstalled discord and BD.
Disabled all other plugs except for timestamps as well

https://i.imgur.com/CVrI0sk.png

**Comment by nosut** [comment]
Bdfdb issue

**Comment by nosut** [comment]
Having the same issue with Keyword tracker.
Not sure if related but:
https://rauenzi.github.io/BDPluginLibrary/docs/#whats-new-in-200
Was linked to the the creator of that plugin when this similar issue was posted in the DB discord.

**Comment by IamNickerson** [comment]
The ZerenpluginLib got an update,
So it maybe had an affect in some of the plugins.

**Comment by Taimoor-Tariq** [comment]
I have looked into it
I'll fix it as soon as I can

**Comment by IamNickerson** [comment]
Okay

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest update

**Comment by IamNickerson** [comment]
Yup it is fixed.
