### ISSUE TITLE
[ BUG | SendTimeStamps ]

### ISSUE THREAD

**Issue by Xeimyn** [Taimoor-Tariq/BetterDiscordStuff#15]
**Button isnt styled the same as upload button**
its a small thing really but the Timestamp button stays centered while the upload button doesent.
Would love to see some type of consistency (either align timestamp also at top or even move the upload button into the center)

Only happens if you have more then 1 line in the text field

![image](https://user-images.githubusercontent.com/72569478/151599148-24f00618-cfe0-4002-9fef-c8abf9ccc6c0.png)

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest update
