### ISSUE TITLE
BetterDiscord plugin repo doesn't have the latest version of SendTimestamps.

### ISSUE THREAD

**Issue by TheGandalf85** [Taimoor-Tariq/BetterDiscordStuff#16]
Don't know where to tell you this, so I'll leave this here.

[https://betterdiscord.app/plugin/SendTimestamps](https://betterdiscord.app/plugin/SendTimestamps)

The above betterdiscord plugin repo doesn't have your latest version of SendTimestamps. I had to install it from here instead.

**Comment by Taimoor-Tariq** [comment]
I have told the website maintainers about this issue, they said that it will be fixed soon.
