### ISSUE TITLE
[ BUG | SendTimestamps ] Manual 'time' change entry causes format value not to update and breaks output

### ISSUE THREAD

**Issue by Wiethoofd** [Taimoor-Tariq/BetterDiscordStuff#18]
Manually changing the date value updates what it displays in 'Format', however doing the same for the time value only updates it the first few times and breaks on consecutive changes afterwards, even using the clock button afterwards doesn't update it.

After the time stops updating in the _Format_ display changing the _Date_ again will then reset the time in the Format display to `12:00 AM`.

At any point after the time stops updating the value in Format clicking the 'Enter' button will output `<t:NaN:f>` in chat instead of a valid Unix-timestamp.

e.g. Time has been changed repeatedly and Format shows incorrect value:
![SendTimeStamps](https://user-images.githubusercontent.com/9917564/158507333-aef786f5-5309-4c82-a47e-a35f5a4ce0dc.png)

**Step to reproduce:**
1. Manually type an hour value starting with a `0`
2. Format now does not update the time section anymore
3. (Optional) Change the minute value to any different value and clicking Enter will now output the `NaN` timestamp
5. (Optional) Use any way to change the Date (manual entry, arrow key to increase or decrease any value or changing from the calendar) and now the Format will display 12AM and not update its time section anymore

**Comment by Taimoor-Tariq** [comment]
Sorry been busy with university stuff.
I will fix it soon.

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest update 🙂
