### ISSUE TITLE
Bddevbadges make sure also it can seen with showbadgesinthechat.

### ISSUE THREAD

**Issue by IamNickerson** [Taimoor-Tariq/BetterDiscordStuff#20]
**Issue**
Explain the bug/issue here
Bddevbadges is not showing with showbadgesinthechat it could be some the badges which are showing could block in the way.

**Comment by Taimoor-Tariq** [comment]
I just added settings for the plugin in the new update, you should be able to disable badges from rendering in the Chat and MemberList.

**Comment by IamNickerson** [comment]
Okay.
