### ISSUE TITLE
SendTimestamps - Move the button to the right in the chat text area

### ISSUE THREAD

**Issue by Malix-Labs** [Taimoor-Tariq/BetterDiscordStuff#23]
Move the button to the right in the chat text area (class="channelTextArea")

### Before
![image](https://user-images.githubusercontent.com/76160668/162378250-49925f54-2832-4175-8037-02ab1d15431b.png)
### After
![image](https://user-images.githubusercontent.com/76160668/162378397-5bd43731-3fe9-4b64-873b-c62291215e4a.png)

**Comment by Taimoor-Tariq** [comment]
Sorry, I don't get what's the issue here, I already have a setting that allows you to move the button to the right. Could you please elaborate on your issue/feature?

**Comment by Malix-Labs** [comment]
I probably didn't see it, I will check asap

**Comment by Malix-Labs** [comment]
Yes, sorry, I checked and there actually was an option for this already
