### ISSUE TITLE
SendTimestamps - Add button to the message edition button area

### ISSUE THREAD

**Issue by Malix-Labs** [Taimoor-Tariq/BetterDiscordStuff#24]
# Add button to the message edition button area

### Before

![image](https://user-images.githubusercontent.com/76160668/162379198-64718efc-5924-4653-a402-a8364852905e.png)

### After

![image](https://user-images.githubusercontent.com/76160668/162379394-529c812b-af65-430a-931d-d9da04b9db46.png)

## Relational Changes

If that is done, timestamp shouldn't be copied from the normal chat text area to the message edition text area

### Current Exemple

_Currently, when you generate a timestamp in the normal chat text area, it gets duplicated in the message edition text area_
![image](https://user-images.githubusercontent.com/76160668/162380224-d0660a21-e840-4db3-8071-b4d8a954a935.png)

**Comment by Malix-Off** [comment]
If that is done, timestamp shouldn't be copied from the normal chat text area to the message edition text area

## Current Exemple
_Currently, when you generate a timestamp in the normal chat text area, it gets duplicated in the message edition text area_
![image](https://user-images.githubusercontent.com/76160668/162380224-d0660a21-e840-4db3-8071-b4d8a954a935.png)

**Comment by Taimoor-Tariq** [comment]
Thanks for bringing this to my attention, I will look into it and hopefully have something working during my summer vacation.

**Comment by Malix-Labs** [comment]
Okay, nice!
Why are you closing the issue tho?

**Comment by Taimoor-Tariq** [comment]
mb I hit comment and close on my end

**Comment by Malix-Labs** [comment]
> mb I hit comment and close on my end

No problem 😄

**Comment by Taimoor-Tariq** [comment]
So I looked into it and currently there is no way to just put the timestamp in the editing textbox, it will always enter it in both the channel textbox and the message edit textbox. It is something that the BdApi does not support.

**Comment by Taimoor-Tariq** [comment]
I figured out a way to do it!
Just released a new version with the fix

**Comment by Taimoor-Tariq** [comment]
Closing issue.
**Reason**: Fixed in v2.0.2

**Comment by Malix-Labs** [comment]
Change the label to "[bug](https://github.com/Taimoor-Tariq/BetterDiscordStuff/labels/bug)" _or even more precise, incorrect (would be nice to create it)_
