### ISSUE TITLE
[ BUG | SendTimestamps ] The icon appears if don't have the send permission.

### ISSUE THREAD

**Issue by sya-ri** [Taimoor-Tariq/BetterDiscordStuff#25]
It doesn't appear in English but seems to appear in other languages.

## :-1: `Danish`, `Japanese`
![](https://user-images.githubusercontent.com/34268371/163666585-9b1a907b-5b13-4182-a6f9-c43e3c0ac8b6.png)
![](https://user-images.githubusercontent.com/34268371/163666629-5004add0-d432-4494-a290-828d911ece91.png)

## :+1: `English, US`, `English, UK`
![](https://user-images.githubusercontent.com/34268371/163666599-42df140f-f5fd-4310-a88c-9a6558bf2692.png)

**Comment by Taimoor-Tariq** [comment]
@sya-ri I am aware of this bug and it is due to me not having my plugins localized for other languages. I am in the middle of exams right now and will be localizing all my plugins during the summer vacation 🙂.

**Comment by sya-ri** [comment]
I see. Your exam is more important than the issue. Good Luck ❤️

**Comment by Taimoor-Tariq** [comment]
Should be fixed in the latest update 💛

**Comment by sya-ri** [comment]
Thank you ❤️ But I haven't tried it yet, I'll check it in a few days 😁 Sorry for waiting 🥲

**Comment by sya-ri** [comment]
Great!!! It works well. Thank you ❤️
