### ISSUE TITLE
[ BUG | SendTimestamps ] relative time has the wrong type letter

### ISSUE THREAD

**Issue by AroLeaf** [Taimoor-Tariq/BetterDiscordStuff#26]
**Issue**
Relative time prints `<t:seconds:r>` but this should be `<t:seconds:R>`

**Comment by Taimoor-Tariq** [comment]
ty for letting me know
I will fix it in the next release

**Comment by Taimoor-Tariq** [comment]
Should be fixed in the latest update 💛

**Comment by TheEeveeLovers** [comment]
If it helps, the issue occurs in line 295 of the script

**Comment by Taimoor-Tariq** [comment]
I just released a new version and it should be fixed 💛

**Comment by Taimoor-Tariq** [comment]
Closing issue.
**Reason:** Fixed in v2.0.1
