### ISSUE TITLE
[ FEATURE | SendTimestamps - Please remember what format I was in between Discord reboots

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#27]
**Feature**
I really love the new {{ <time> }} feature.  The only problem is the format reverts back to the default when I reboot Discord and I prefer the "2:00 PM" format.  It's fine if I set it and then don't reboot Discord, but it would be great if it remembered the format I was last in between reboots.

Thank you.  This is my absolute favorite plugin.  Have a great day!

**Comment by Taimoor-Tariq** [comment]
Hi,
The plugin should remember the last used format on reboot, I will look into it and fix it in the next release.
Thank you for using my plugin, I'm glad you like it 💛.

**Comment by Taimoor-Tariq** [comment]
I just tested the plugin and it remembers it fine on my client, try deleting the plugin and config from the plugins folder ![image](https://user-images.githubusercontent.com/45585081/165854114-c21712ed-3e75-400a-8a4c-514888778812.png)
And then download it again [link](https://www.taimoor.me/api/bd/SendTimestamps.plugin)

**Comment by Taimoor-Tariq** [comment]
Let me know if this worked so I can close the issue.

**Comment by rexkix** [comment]
It worked once fine, but somehow my format has now reverted back to full (e.g. "Saturday, April 30, 2022 2:00 PM").  I don't know why.  I assumed it was because I rebooted Discord.  I've also rebooted my computer.

I'll try to figure out what makes it revert format.

I did notice you said in today's update that you can put the format in text, but I don't know what values to use for each format.

**Comment by rexkix** [comment]
Hmmm.  Time passes.  It seems to always prefer to use the full format unless I change the popup that appears as I type the text.  This is regardless of the last state of the drop-down.  I can change the format by changing the popup's drop-down, but that's the only way I don't get full format.

**Comment by Taimoor-Tariq** [comment]
I released a new version, should be fixed now 💛

**Comment by Taimoor-Tariq** [comment]
Closing issue.
**Reason**: Fixed in v2.1.4
