### ISSUE TITLE
[ BUG | (SendTimestamps) ] Button not visible in DM-s

### ISSUE THREAD

**Issue by TheChilliPL** [Taimoor-Tariq/BetterDiscordStuff#28]
The button opening the timestamps modal doesn't show up in direct messages.

Server:
![image](https://user-images.githubusercontent.com/18823939/165849927-d25eb769-b0ff-4e8c-8566-82d19fe98ce6.png)
DM-s:
![image](https://user-images.githubusercontent.com/18823939/165849971-6a064807-c421-465d-9395-5fa9f1f21e83.png)

**Comment by Taimoor-Tariq** [comment]
Ty for letting me know.
I will look into it and fix it in the next release

**Comment by Taimoor-Tariq** [comment]
I just released a new version and it should be fixed 💛

**Comment by TheChilliPL** [comment]
Wow, that was a very quick fix, seems to work perfectly!
