### ISSUE TITLE
[ FEATURE | (SendTimestamps) ] Show send timestamps in the “new” menu

### ISSUE THREAD

**Issue by TheChilliPL** [Taimoor-Tariq/BetterDiscordStuff#29]
It would be great if the button could be moved to the menu with the plus icon, where normally you can send files or create threads.
![image](https://user-images.githubusercontent.com/18823939/165850223-b8291048-76eb-4068-bb28-41205c6e62c1.png)

**Comment by Taimoor-Tariq** [comment]
Sorry, I tried doing this when I first made the plugin and it is not possible to do this with the current API we have.

**Comment by TheChilliPL** [comment]
Wouldn't it be possible manually with the [DOM mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)? It would probably be a bit harder to do, but it would just require detecting when Discord creates this popup and adding an element there, I believe

**Comment by Taimoor-Tariq** [comment]
I will look into it in the next week

**Comment by Taimoor-Tariq** [comment]
I figured out a way to do it, It's in the version I just released!

**Comment by TheChilliPL** [comment]
Wow, that was really fast!
It seems to work well, although I can only see one tiny problem with styling:
![image](https://user-images.githubusercontent.com/18823939/165927950-77c9ce42-d19d-44f8-8457-747a0ce78bca.png)
![image](https://user-images.githubusercontent.com/18823939/165927957-1f71a4db-558a-4408-9be2-f5ac808e3ef7.png)
The button, unlike any other, doesn't have the blue glow on hover. Also, if you hover at any other button after this one, it doesn't get the hover effect:
![image](https://user-images.githubusercontent.com/18823939/165928052-8ae167ea-f9ed-4cd0-8683-0bb3a3369f44.png)
For some unknown reason, the effect isn't done with the `:hover` pseudoclass, but with JS, adding the `focused-3qFvc8` class to the label container element. If my research in devtools is correct, t's added by Discord in the `pointerenter` event and removed in the `mouseout` event handlers. The weird thing is that the `pointerenter` event doesn't seem to fire on the file send button if moving the mouse from the timestamp button, not sure why that is

**Comment by Taimoor-Tariq** [comment]
I already had this implemented but didn't test it without my theme lol. I fixed it and it should work properly now.
Let me know if it works for you 💛

**Comment by TheChilliPL** [comment]
It does work unless I move my mouse back to the “send a file” button 🤔 
![image](https://user-images.githubusercontent.com/18823939/166117271-cf0c2180-95ab-4335-bbc1-de510751a11e.png)

**Comment by Taimoor-Tariq** [comment]
I released a new version, should be fixed now 💛

**Comment by TheChilliPL** [comment]
Out of curiosity, why did it happen and how did you fix that? 🤔
Thanks for the update, works flawlessly now!

**Comment by Taimoor-Tariq** [comment]
I just added another event listener to the "upload option" in the menu 😆.
