### ISSUE TITLE
[ FEATURE | SendTimestamps ] Allow specifying format in the message send replacement

### ISSUE THREAD

**Issue by TheChilliPL** [Taimoor-Tariq/BetterDiscordStuff#30]
Right now, it's possible to send a timestamp by writing something like `{{dec 2 2020}}` or `{{10:40am}}` and sending the message, but it doesn't let you configure the format. To do that, you need to open the dialog.
What could be done is allowing to specify the format in a similar manner, like `{{DATETIME|FORMAT}}`, e.g. `{{2022-04-30 8:00|R}}` would say something like `in 21 hours`, using the `R` relative time format

**Comment by Taimoor-Tariq** [comment]
I just released a new version that allows you to select the formats before sending. But your idea is great too (if you know your formats 🙂) so I might think of adding it later.

**Comment by TheChilliPL** [comment]
Works very well, but the popup position is fixed to the bottom border of the screen. It covers the textbox if it's multiline

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest version 💛

**Comment by Taimoor-Tariq** [comment]
Closing issue.
**Reason**: Fixed in v2.1.3
