### ISSUE TITLE
[ FEATURE | (Send Timestamps) - Let me enter {{ 2 pm }} 

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#31]
**Feature**
Usually I just want a time on the hour.  Please let me enter {{ 2 pm }} instead of requiring I enter {{ 2:00 pm }}.
Thank you.

**Comment by Taimoor-Tariq** [comment]
Added in the latest version 💛

**Comment by Taimoor-Tariq** [comment]
Closing issue.
Reason: Added in v2.1.3
