### ISSUE TITLE
[ BUG | (Sendtimestamps) Changelog typo

### ISSUE THREAD

**Issue by KawaiiTemDev** [Taimoor-Tariq/BetterDiscordStuff#32]
**Issue**
In the changelog you wrote "fromat" instead of format

![image](https://user-images.githubusercontent.com/25987110/166118767-547974a8-c6ed-4fe6-b4df-bcd1f3407d00.png)

**Comment by Wiethoofd** [comment]
Also `sometines` on the last line with an N instead of M.

**Comment by Taimoor-Tariq** [comment]
Closing issue.
**Reason**: Fixed in v2.1.4
