### ISSUE TITLE
[ BUG | SendTimestamps ] Invalid output when inline timestamp edited before sending

### ISSUE THREAD

**Issue by TheChilliPL** [Taimoor-Tariq/BetterDiscordStuff#33]
I put in a date:
![image](https://user-images.githubusercontent.com/18823939/166272333-85038c56-f198-4c07-822b-daa77789b21c.png)
I change the day, the preview seems correct:
![image](https://user-images.githubusercontent.com/18823939/166272247-2c3e1ee3-b2c7-4a7c-8823-edefab4e595a.png)
The original time gets output:
![image](https://user-images.githubusercontent.com/18823939/166272101-daa8c604-0c41-429d-ba9e-e81478430760.png)

Also, if I try to edit the message and replace the output with a new inline timestamp thing, and try sending it, the plugin doesn't seem to replace it:
![image](https://user-images.githubusercontent.com/18823939/166275174-745926bc-34d0-475c-88d0-76c72aea0875.png)
![image](https://user-images.githubusercontent.com/18823939/166275341-7e113434-29d0-4539-9f68-71682fcf6979.png)

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest version 💛.

P.S. you actually have to make some changes to the message as discord does not fire an edit event if nothing is edited.

**Comment by TheChilliPL** [comment]
By the way, with explicit formats specified in the string itself it would be possible to convert the Discord timestamp thing (<t:timestamp:format>) back into your double bracket thing, right? It would be so nice if it actually happened when editing a message!

**Comment by TheChilliPL** [comment]
Is there any reason the plugin resets seconds back to zero?
![image](https://user-images.githubusercontent.com/18823939/166341550-45ac051e-dd76-4bd9-a384-ef906a9878c6.png)
Also after sending: ![image](https://user-images.githubusercontent.com/18823939/166341605-2e8b3e01-5667-4d7c-ad88-4633d1f972c8.png)

**Comment by TheChilliPL** [comment]
(Adding 59 to the timestamp manually does work)

**Comment by Taimoor-Tariq** [comment]
> Is there any reason the plugin resets seconds back to zero?

I will look into this and fix it.


­
> It would be so nice if it actually happened when editing a message!

Currently, this is not possible as there is no proper way for me to get the current content of a message int the text area. If I can find a way to get this I will add it to the plugin.

**Comment by TheChilliPL** [comment]
The editing bug seems to be back @Taimoor-Tariq
