### ISSUE TITLE
[ BUG | (SendTimestamps) - Entering more than one text timestamp in a message doesn't work right

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#37]
**Issue**
It doesn't work right when I enter more than one timestamp in a message.

For instance "{{ 1 pm }} to {{ 2 pm }}" sometimes reverses the order.  Sometimes one gets replaced by the other.  Sometimes a lot of things.  I've delayed reporting this, trying to establish the pattern, but I can't figure it out.

It may be a Discord problem, because I've seen it convert the timestamps to Discord-like text and then it still makes mistakes.

**Comment by Taimoor-Tariq** [comment]
I'll look into it when I get my laptop back.

**Comment by rexkix** [comment]
Hi.  Welcome back to the project.
1. The string "{{ 12 pm }} to {{ 1 pm }}" doesn't work.  It converts the first one, but not the second.
2. Please consider releasing to the repo if you think you're done.  I captured your code correctly though.  At least I think I did.
This is the feature I most want right now.  I do this kind of thing all the time.
Thanks. :)

**Comment by rexkix** [comment]
Hi there.  Please see the previous comment.
This issue is closed, but the problem still exists.
I was assuming you were still very busy.  I hope you haven't forgotten about this plugin.  It's awesome.
Also, please release to the repo.  Others deserve to have your most recent bug fixes.
