### ISSUE TITLE
[ BUG | SendTimestamps - {{ 2 pm }} doesn't work now

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#38]
**Issue**
When I type "{{ 2 pm}}" I get a message "Error formating this timestamp".

Also, the word should be "formatting" with two "t"s.  No big deal there, just trying to help.

**Comment by Taimoor-Tariq** [comment]
Hey, sorry for the late reply.
I won't be having my laptop with me for the next 3 weeks (I sent it for repairs) so I can't really do any Dev work for the time being.
I will definitely try to fix it as soon as I get my laptop back.

**Comment by TheChilliPL** [comment]
It seems like it stopped working completely
![image](https://user-images.githubusercontent.com/18823939/169403623-4e93ede1-cef2-449c-8c14-5df743ba16a3.png)
Inserting these through the menu does still work, on the other hand

**Comment by simpleshawn** [comment]
[Screenshot_97](https://user-images.githubusercontent.com/79335438/169887793-f6840659-256b-4736-8800-f563458c6395.png)
Alright i'm getting into it! Wish me luck (ps : as a lua programmer which puts his legs onto json/css haha)

**Comment by simpleshawn** [comment]
Yeah alright I've got a lot of progress, it's over except for ONE single thing, does someone know how to create Discord's Channel Text Area Container (you know the chat bar), including Zeres Library ofc.

**Comment by rexkix** [comment]
Hi Taimoor.  Sorry to add a comment to an issue just to reach out like this, but I don't know how to contact you otherwise.
Last we talked, you were separated from your laptop and couldn't work on this project, but that's a long time ago.
Are you still around?  Is your laptop nevermore?
I hope you (or somebody else) can fix this and other issues because I really like this plugin.
Thank you,

**Comment by Taimoor-Tariq** [comment]
Hey, I'm back but have been busy with a lot of university stuff. 
I did update this plugin to version 2.1.7 which works fine on my client. Could you try deleting the "SendTimestamps.plugin.js" and the "SendTimestamps.config.json" files in the plugins folder and download the plugin from github.

**Comment by rexkix** [comment]
Welcome back.  I've verified this works again.
