### ISSUE TITLE
[ BUG | SendTimestamps ] "F" only showing except ...

### ISSUE THREAD

**Issue by simpleshawn** [Taimoor-Tariq/BetterDiscordStuff#39]
**Issue**
Basically, when you put a timestamp with the menu or the {{...}}, for whatever reason, it writes F on the final message, except if you don't put any modifier after it (for example : <t:xxxxxxxxx> instead of <t:xxxxxxxxx:F>)

I played a bit with the code and figured out that you have to change :
The two `return this.sendFomrmatOptions[n++]` 
into `return this.sendFomrmatOptions[opts.key]`

**UwU**

**Comment by rexkix** [comment]
1. It appears that the PR only changes one instance of this line at 819.  As the comment above indicates, there is a second instance at 833.  Changing the one line did not help, but changing both did.

2. The "{{ 2:00 pm }}" trick doesn't work with this fix.  I have to use the menus.

Please understand that I am a novice at this stuff.  Thanks.

**Comment by Malix-Labs** [comment]
@rexkix please forward your answer to #40 comments _😊_
_~if you don't do it within a day I would no problem 👌~_

**Comment by Malix-Labs** [comment]
_[Done](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40#issuecomment-1133952691), Thanks ❤️_

**Comment by Simak90** [comment]
> 1. It appears that the PR only changes one instance of this line at 819.  As the comment above indicates, there is a second instance at 833.  Changing the one line did not help, but changing both did.
> 2. The "{{ 2:00 pm }}" trick doesn't work with this fix.  I have to use the menus.
> 
> Please understand that I am a novice at this stuff. Thanks.

Yeah I didn't check into the {{}} stuff I'll do that tmrw (just wanted dates to work at first I prefer the menu than writing)
Edit : what's a PR?

**Comment by Malix-Labs** [comment]
@Simak90 

> what's a PR?

PR = [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by Malix-Labs** [comment]
Also

@Simak90 

> Yeah **I** didn't check into the {{}} stuff

Are you the same person as @simpleshawn ~or @MomoMiles~?

**Comment by Simak90** [comment]
> Also
> 
> @Simak90
> 
> > Yeah **I** didn't check into the {{}} stuff
> 
> Are you the same person as @simpleshawn?

Yeah I don't have the same email on my phone and stuff than on my pc, only than simple shawn idk about momomiles

**Comment by Malix-Labs** [comment]
@Simak90

Ok

Also there is already a [pull request about that](#40) : #40

**Comment by Malix-Labs** [comment]
#44
