### ISSUE TITLE
[ INCORRECT | SendTimestamps ] "fomrmat" instead of "format"

### ISSUE THREAD

**Issue by Malix-Labs** [Taimoor-Tariq/BetterDiscordStuff#42]
In a file, "format" is written "fomrmat"

_I will enhance this description later_

**Comment by Simak90** [comment]
Basically any value containing "Format" don't exist he just used all along the script "Fomrmat" or "Fomrat" but there is no problem about that imo

**Comment by Malix-Labs** [comment]
@Simak90

> Basically any value containing "Format" don't exist

What do you mean by that?

**Comment by Simak90** [comment]
What I mean is that the value can also be called x or fathead if you replace every "Fomrmat" by those the script will work as well as originally.
By that what I really mean is I don't see the problem of the thread since the script still works

**Comment by Malix-Labs** [comment]
@Simak90

> What I mean is that the value can also be called x or fathead if you replace every "Fomrmat" by those the script will work as well as originally. By that what I really mean is I don't see the problem of the thread since the script still works

Yes, it obviously would work, I just found it weird 😄
