### ISSUE TITLE
[ BUG | Sendtimestamps] ...

### ISSUE THREAD

**Issue by Willytor** [Taimoor-Tariq/BetterDiscordStuff#45]
Sending timestamps, either from the menu or directly, that isn't in the T format gets immediately replaced with the letter "F". Only happens with auto replace on.

**Comment by simpleshawn** [comment]
Check my thread, basically replace the two "n++" by "opts.key"

**Comment by ironman9356** [comment]
Yeah same all my timestamps are being converted to F
> Check my thread, basically replace the two "n++" by "opts.key"

this works btw

**Comment by jack652** [comment]
same thing here
all timestamps replaced by F

**Comment by Taimoor-Tariq** [comment]
Try deleting both "SendTimestapms.plugin.js" and "SendTimestamps.config.json" from your plugins folder and download the latest version of the plugin from GitHub.

**Comment by ilyvion** [comment]
Deleting both files and re-downloading fixed this replaced-by-F problem for me at least. Weird that I manually would have to do such a thing, though.
