### ISSUE TITLE
[ Timestamp not working | SendTimestamps ] 

### ISSUE THREAD

**Issue by Canada-LaVearn** [Taimoor-Tariq/BetterDiscordStuff#47]
**Issue**
When sending a timestamp, after choosing what date or time I need, the timestamp converts to the letter F. Oddly this does not happen to the second timestamp in a message

Images:

![image](https://user-images.githubusercontent.com/80727688/178898264-b081dca2-1bd2-4c31-806a-796918eac8c2.png)

after sending

![image](https://user-images.githubusercontent.com/80727688/178898321-488094a8-68ef-47fa-8b57-58acb40647a2.png)

**Comment by Taimoor-Tariq** [comment]
Will look into it

**Comment by harvanchik** [comment]
Been having the same problem for months.

**Comment by EpicGazel** [comment]
For the time being, just delete ":f"

**Comment by KensonPlayz** [comment]
Any updates on the fix for this? So we don't have to delete the :f bit?

**Comment by nick22985** [comment]
#48 solves this

**Comment by aaronliu0130** [comment]
Isn't this already fixed, without the pr?

**Comment by nick22985** [comment]
no it does that t string thing because they changed the way how children nodes are defined so it doesn't point to the array.
https://gyazo.com/7fa1ec91153b6d533547a5f7c740052d
so u dont get the menu and the formats go weird

**Comment by aaronliu0130** [comment]
Well on mac I don't get this issue on the newest code without the pull request. Plus, that gyazo menu is a feature I'm sure. The regular menu still works. Plus, nesting props.children in props.children is pretty idiotic from a programming standpoint. I currently don't have access to my windows computer so I dunno if this is a windows specific issue.

**Comment by aaronliu0130** [comment]
Plus, nesting props.children in props.children is pretty idiotic from a programming standpoint.

**Comment by nick22985** [comment]
Without `ret.props.children` error:
https://gyazo.com/def401cbe922ad8d468647c76c9faff7

The data structure of the object:
`ret.props`
https://gyazo.com/b8cb065111f118c201680f5b81139882

as seen in the data structure children is actually not an array therefore you can not push props to it. where `ret.props.children.props.children` is the first instance of an array in the object also looking at the dev console it seems that it is the correct place for it above the message box.

as it is a react app idk why the mac implementation would be different from the windows one. What version of discord are you running? The regular menu never stopped working it was just sending a message that removed the timestamp and put a straight `F` after sending even if you had the timestamp correctly in chat. https://gyazo.com/c0daeb03562bd9ea65716e981d1bb3ec
When disabling the plugin it sent the time correctly formatted leading me to dig into the console to figure out what was going on

**Comment by aaronliu0130** [comment]
> The regular menu never stopped working it was just sending a message that removed the timestamp and put a straight F after sending even if you had the timestamp correctly in chat.

I know this. I also had this thing before I copied the new source code without the pull request into the plugin file. It then proceeded to work.

Stable 138734 (047115f)
BetterDiscord 1.5.3
Host 0.0.267 OS X 10.15.7 (19.6.0)

**Comment by nick22985** [comment]
Stable 138734 (047115f)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)

> I know this. I also had this thing before I copied the new source code without the pull request into the plugin file. It then proceeded to work.

weird when i pull from master and use it still get the same issue. Don't have a easy way to test mac sadly

**Comment by Taimoor-Tariq** [comment]
Hey guys,
Sorry for being inactive for too long. I had a lot going on so I was not able to fix bugs. As you may know that the recent Discord update broke a lot of the plugins. I will attempt to fix my plugins once I figure out what the broken changes are 💛.
