### ISSUE TITLE
[ BUG | SendTimeStamps ] Plugin replaces all timestamps with F

### ISSUE THREAD

**Issue by LeonTheDev-io** [Taimoor-Tariq/BetterDiscordStuff#49]
**Issue**
No matter what type of timestamp I send, as soon as I send it it will be turned into "F" for everyone

**Comment by ghost** [comment]
to add: only the first timestamp in a message is changed to F. Both Epoch (<t:1659364216:t>) and plugin converted ({{10:30 am}}) are affected. If a picture is attached all conversions are done properly.

**Comment by RedMan13** [comment]
i found the issue i think
its with the component on line 226. removing fixes this
so far i haven't ran into any errors with removing it

**Comment by ArjhanToteck** [comment]
Removing this part fixed it for me:

`this.sendFomrmatOptions = {
0: 'F',
};`

**Comment by Cutinup99** [comment]
> Removing this part fixed it for me:
> 
> `this.sendFomrmatOptions = { 0: 'F', };`

Mine was split across multiple lines, but simply removing that whole thing no longer allows you to use the {{ }} date entry method, however, the button still works

**Comment by Taimoor-Tariq** [comment]
Hey guys,
Sorry for being inactive for too long. I had a lot going on so I was not able to fix bugs. As you may know that the recent Discord update broke a lot of the plugins. I will attempt to fix my plugins once I figure out what the broken changes are 💛.
