### ISSUE TITLE
[ BUG | SendTimestamps - Using multiple text stamps (i.e. "{{ 1 pm}} to {{ 2 pm }}" doesn't work right

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#52]
Saying "{{ 1 pm}} to {{ 2 pm }}" doesn't work right.  I think it converts the first timestamp, but not the second.

This is the same as Issue #37, but you closed that one.  I've tried commenting there, hoping to get it reopened.  I'm doing this to reopen it.  Apologies if this is not the correct process.

**Comment by Taimoor-Tariq** [comment]
I will look into this when I remake the plugin

**Comment by Taimoor-Tariq** [comment]
Check announcement in issue #58 [Issue](https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/58#issuecomment-1361206186)
