### ISSUE TITLE
[ QUESTION | SendTimestamps] ...

### ISSUE THREAD

**Issue by datlmhg** [Taimoor-Tariq/BetterDiscordStuff#55]
how can i change "Date" to dd/mm/yy ?

and "Format" to : [day of the week] + [day of the month] + [month] + [year]
![image](https://user-images.githubusercontent.com/86174857/189488928-c47ddb20-c5aa-4858-8332-671a6499e7b7.png)

**Comment by Taimoor-Tariq** [comment]
It is currently not possible and I will have to make a custom input instead of using Discord's. I will look into it in the future since this is very low priority on my list.
