### ISSUE TITLE
[Suggestion] Sendtimestamps - Allow option to move clock icon back to right side of message bar

### ISSUE THREAD

**Issue by Caketaco** [Taimoor-Tariq/BetterDiscordStuff#6]
![image](https://user-images.githubusercontent.com/39420594/139564625-a3642d60-7a4d-4eb5-9801-66b41384507b.png)
_(Visual representation of solution)_

The latest update moved the clock to the left with no option to move it back. I prefer it the way it previously was. I have no option to revert it back to its previous position.

**Comment by Jorgen1040** [comment]
Noticed the same thing, but I have another suggestion. Instead of cluttering the message bar, move the icon to the menu that opens when you click on the plus. 

![image](https://user-images.githubusercontent.com/26395020/139670922-d5779084-e038-4204-9e9b-e4a09938e602.png)

**Comment by Caketaco** [comment]
As of the latest update, the original issue is fixed! Thank you so much!
