### ISSUE TITLE
SendTimestamps isn't working anymore

### ISSUE THREAD

**Issue by ilyvion** [Taimoor-Tariq/BetterDiscordStuff#6]
I don't know what happened, but when I click the Settings button, I get:
![image](https://user-images.githubusercontent.com/767490/149214660-a1ea77ca-fb60-41d8-b4fa-d3d5e1595c26.png)
and the clock icon has disappeared from the input box (used to be where I drew the red box):
![image](https://user-images.githubusercontent.com/767490/149215193-d864fece-4bf0-407d-958e-47d8739e5254.png)

I'm on v1.1.3 of the plugin.

**Comment by ilyvion** [comment]
Oh, here's the contents of the `SendTimestamps.config.json` file, in case that matters:
```json
{
    "currentVersionInfo": {
        "version": "1.1.3",
        "hasShownChangelog": true
    }
}
```

**Comment by ilyvion** [comment]
Oh yeah, I do find it suspicious that your code does `document.querySelector(".buttons-3JBrkn")` while in my client, that CSS class is apparently named `buttons-uaqb-5`. In fact, several of the CSS classes look wrong. When I did

```
buttons-3JBrkn -> buttons-uaqb-5
buttonContainer-28fw2U -> buttonContainer-2lnNiN
button-318s1X/button-38aScr -> button-f2h6uQ
lookBlank-3eh9lL -> lookBlank-21BCro
```

the button came back and looked correct again.

Makes me wonder if there is a more robust way of finding these values.

**Comment by Taimoor-Tariq** [comment]
Ill try to fix it as soon as I can
