### ISSUE TITLE
[ BUG | SendTimestamps ] Not Compiling

### ISSUE THREAD

**Issue by code-fanatic** [Taimoor-Tariq/BetterDiscordStuff#61]
**Issue**
Not Compiling

[optional but helpful: screenshots, plugin config]
![image](https://user-images.githubusercontent.com/65089197/208288212-69e55e1b-7c96-4f86-bace-8426d33218ba.png)

**Comment by zisra** [comment]
Same issue here

**Comment by Taimoor-Tariq** [comment]
Check announcement in issue #58 [Issue](https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/58#issuecomment-1361206186)
