### ISSUE TITLE
[ BUG | SendTimestamps ] Plugin broken

### ISSUE THREAD

**Issue by TIMOFEITV** [Taimoor-Tariq/BetterDiscordStuff#64]
don't know what's causing the problem but, here the error that spit out when I tried to run it.

![image](https://github.com/Taimoor-Tariq/BetterDiscordStuff/assets/134606033/a0b07c82-756a-4392-8adb-05509f275930)

I'm not a big code guy but I'm not sure what this is supposed to be.

**Comment by ArcturusLight1** [comment]
The plugin is discontinued, and I think the author forgot to take it off betterdiscord.

**Comment by TIMOFEITV** [comment]
ah, sad. I would love to see this Plugin in use.
