### ISSUE TITLE
SendTimestamps Plugin icon is not showing up in Discord Text Bar.

### ISSUE THREAD

**Issue by IamNickerson** [Taimoor-Tariq/BetterDiscordStuff#7]
Hey,
The Send Timestamps plugin icon is not showing in the Text bar even it got an update it is still not showing up.

**Comment by IamNickerson** [comment]
Still with an update it is not still not showing up

**Comment by Taimoor-Tariq** [comment]
Can you give me more info on the bug, screenshots or configs for example?

**Comment by IamNickerson** [comment]
Ok the problem is that Icon of the Send timestamps plugin isn't showing after when you released a update patch to fix it 
![image](https://user-images.githubusercontent.com/61643704/149447119-b76d01e5-37b0-426d-b7a3-e7bd1a3e4ded.png)
It is still not showing. I even tried opening the plugin settings it says couldn't not open settings for Sendtimestamps.
![image](https://user-images.githubusercontent.com/61643704/149447290-40ae7ff2-19f0-4df2-8fa9-59f81ce2f625.png)
If u want code of your plugin I am having right now. Here you go..
[SendTimestamps.plugin.txt](https://github.com/Taimoor-Tariq/BetterDiscordStuff/files/7867679/SendTimestamps.plugin.txt)
I cant put js scripts it is not allowing me don't worry it doesn't contain any malware it is code of your plugin which I am having right now.
I tried even to enable and disable it and enable it also tried reinstall the plugin and it is still not showing the icon and even the settings.

**Comment by Taimoor-Tariq** [comment]
ty for the screenshots, I will look into the issue and fix it as soon as I can

**Comment by Taimoor-Tariq** [comment]
Should be fixed in the latest update. 🙂

**Comment by IamNickerson** [comment]
Ok fixed.
