### ISSUE TITLE
[Suggestion] Separate dropdowns to select hours and minutes

### ISSUE THREAD

**Issue by ArcWandx86** [Taimoor-Tariq/BetterDiscordStuff#7]
This current dropdown of 1400+ entries does technically work, and while I can navigate it fine with an infinite scroll wheel, it's still super laggy and less than ideal. Having two dropdowns (one for hours and one for minutes) would solve this. Ideally though, I think an input box where we can directly type the time would be better.

Since I haven't personally worked on this, I'm not exactly familiar with it all. As such, I'd love to know what technical challenges there are to this

**Comment by Taimoor-Tariq** [comment]
I will work on using text boxes in the next update
