### ISSUE TITLE
SendTimestamps button in send text message area has weird formatting when set to be on the left with position 1

### ISSUE THREAD

**Issue by drjaska** [Taimoor-Tariq/BetterDiscordStuff#8]
![image](https://user-images.githubusercontent.com/88596812/149325158-32c5990e-9e20-480a-aa1d-745bf7536560.png)

I couldn't replicate this with any other plugin settings combination than side left with position 1. 

Discord for Linux Ubuntu desktop. Aspect ratio 16:9.

**Comment by Taimoor-Tariq** [comment]
Apparently its a bug on all platforms and ill fix it as soon as possible

**Comment by Taimoor-Tariq** [comment]
Should be fixed in the latest update. 🙂

**Comment by nosut** [comment]
> 

Still having this issue in a server
