### ISSUE TITLE
[VoiceUtilities] - Menu not shown

### ISSUE THREAD

**Issue by Dschogo** [Taimoor-Tariq/BetterDiscordStuff#9]
Hey awesome plugin, as stated in the title, the menu stopped showing. Couldnt fix it myself with my basic scripting knowledge. 

Tried on all DC channels (Stable, PTB, Canary), gone everywhere.

**Comment by Taimoor-Tariq** [comment]
Hey,

I haven't update this plugin in a while as it was rejected due to performance loads. I will work on rebuilding the plugin soon and release it.
