### ISSUE TITLE
Unable to install, plugin can not be compilled when loaded from disk or plugin repo

### ISSUE THREAD

**Issue by josh-stableprice** [Taimoor-Tariq/BetterDiscordStuff#9]
This is the sum total of the reported error

![image](https://user-images.githubusercontent.com/46674140/149337147-8178550a-e629-4ee2-8283-ae8d16990094.png)

**Comment by Taimoor-Tariq** [comment]
Go to this link https://raw.githubusercontent.com/Taimoor-Tariq/BetterDiscordStuff/main/Plugins/SendTimestamps/SendTimestamps.plugin.js
then press **ctrl + s** and then save the file in your plugins folder.

Let me know if it still gives that error.

**Comment by Taimoor-Tariq** [comment]
I just released an update so download the latest update and let me know if it's still bugging out

**Comment by josh-stableprice** [comment]
That seemed to work

**Comment by Ledinax** [comment]
Still bugged for me
